version: '3.8'

services:
  server:
    build: ./server
    command: npm run start:dev
    working_dir: /app
    volumes:
      - ./server:/app
    environment:
      PORT: 3000
    ports:
      - "3000:3000"
    links:
      - mongodb

  frontend:
    build: ./frontend
    command: npm run start
    working_dir: /app
    volumes:
      - ./frontend:/app
    ports:
      - "4000:4000"

  public:
    image: nginx
    ports:
      - "8180:8080"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./frontend/build:/usr/share/nginx/html

  mongodb:
    image: mongo
    ports:
      - "27017:27017"
